#!/bin/sh
sudo apt-get install python-dev; 
sudo apt-get install libxml2-dev; 
sudo apt-get libxslt-dev;
sudo apt-get install python-glpk;
sudo apt-get install m4;
sudo apt-get install python-pip;
sudo apt-get install nodejs-legacy;
sudo apt-get install npm;
wget https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2;
tar -xjvf gmp-6.1.0.tar.bz2;
cd gmp-6.1.0;
./configure;
sudo make install;
wget http://ftp.gnu.org/gnu/glpk/glpk-4.47.tar.gz;
tar -xzvf glpk-4.47.tar.gz;
cd glpk-4.47;
./configure;
sudo make install;
cd ..;
wget http://tfinley.net/software/pyglpk/pyglpk-0.3.tar.bz2;
tar -xjvf pyglpk-0.3.tar.bz2; 
cd pyglpk-0.3;
make;
make install;
cd ..;
