#!/bin/sh
sudo apt-get install python-dev; 
sudo apt-get install libxml2-dev; 
sudo apt-get libxslt-dev;
sudo apt-get install python-glpk;
sudo apt-get install m4;
sudo apt-get install python-pip;
sudo apt-get install nodejs-legacy;
sudo apt-get install npm;
wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2;
tar -xjvf gmp-6.1.2.tar.bz2;
cd gmp-6.1.2;
./configure;
sudo make install;
cd ..;
wget http://ftp.gnu.org/gnu/glpk/glpk-4.61.tar.gz;
tar -xzvf glpk-4.61.tar.gz;
cd glpk-4.61;
./configure;
sudo make install;
cd ..;
wget https://github.com/bradfordboyle/pyglpk/archive/master.zip;
unzip master.zip; 
cd pyglpk-master;
make;
make install;
cd ..;
